CREATE TABLE IF NOT EXISTS files (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  filename TEXT NOT NULL,
  size INTEGER NOT NULL,
  mime TEXT,
  checksum TEXT,
  path TEXT NOT NULL,
  created_at DATETIME NOT NULL
);